export const BOOKING_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  CANCELLED_BY_TOURIST: "CANCELLED_BY_TOURIST",
  CANCELLED_BY_GUIDE: "CANCELLED_BY_GUIDE",
  EXPIRED: "EXPIRED",
};

export const BOOKING_STATUS_VALUES = Object.values(BOOKING_STATUS);

export const COUPON_STATUS = {
  AVAILABLE: "AVAILABLE",
  RESERVED: "RESERVED",
  USED: "USED",
  EXPIRED: "EXPIRED",
};

export const COUPON_STATUS_VALUES = Object.values(COUPON_STATUS);

export const CANCELLATION_ACTOR = {
  TOURIST: "TOURIST",
  GUIDE: "GUIDE",
};

export const BOOKING_LIMITS = {
  MIN_GROUP_SIZE: 1,
  MAX_GROUP_SIZE: 8,
  MAX_MEMBER_NAME_LENGTH: 100,
  PAYMENT_WINDOW_MINUTES: 15,
  COUPON_VALIDITY_DAYS: 90,
  COUPON_DISCOUNT_PERCENTAGE: 10,
  TOURIST_REFUND_HOURS_THRESHOLD: 24,
  TOURIST_REFUND_PERCENTAGE: 70,
  GUIDE_REFUND_PERCENTAGE: 100,
  GUIDE_RATING_PENALTY: 0.5,
  DEFAULT_RATING: 5,
  MIN_RATING: 0,
  MAX_RATING: 5,
};

export const BOOKING_DEFAULTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  DEFAULT_SORT: "-createdAt",
};

export const BOOKING_SORT_FIELDS = {
  createdAt: "createdAt",
  slotDate: "slot.date",
};
