import { SUPPORTED_LANGUAGE_CODES } from "./languageTestConstants.js";

export const SUPPORTED_GUIDE_LANGUAGES = SUPPORTED_LANGUAGE_CODES;

export const GUIDE_PROFILE_LIMITS = {
  MIN_LANGUAGES: 1,
  MAX_LANGUAGES: 10,
  MAX_BIO_LENGTH: 1000,
  MAX_INTERESTS: 15,
  MAX_INTEREST_LENGTH: 50,
  MAX_EXPERIENCE_YEAR_LENGTH: 50,
};

export const EXPERIENCE_PHOTO_CLOUDINARY_FOLDER = "guide-profile/experience";
