export const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export const VERIFICATION_STATUS_VALUES = Object.values(VERIFICATION_STATUS);

export const DOCUMENT_VERIFICATION_STATUS = {
  NOT_SUBMITTED: 'NOT_SUBMITTED',
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export const DOCUMENT_VERIFICATION_STATUS_VALUES = Object.values(DOCUMENT_VERIFICATION_STATUS);

export const LANGUAGE_TEST_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  PENDING: 'PENDING',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
};

export const LANGUAGE_TEST_STATUS_VALUES = Object.values(LANGUAGE_TEST_STATUS);

export const ACCOUNT_VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export const ACCOUNT_VERIFICATION_STATUS_VALUES = Object.values(ACCOUNT_VERIFICATION_STATUS);

export const PASSPORT_VERIFICATION_STATUS = {
  NOT_SUBMITTED: 'NOT_SUBMITTED',
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

export const PASSPORT_VERIFICATION_STATUS_VALUES = Object.values(PASSPORT_VERIFICATION_STATUS);
